### ISSUE TITLE
Upgrade to netcoreapp3.0?

### ISSUE THREAD

**Issue by sdcb** [sketch7/dotnet-ngx-sample#1]
This is awesome :) And dotnet core 3.0 is out, any plan to upgrade this to 3.0?

**Comment by stephenlautier** [comment]
Most probably I will, but I think I will wait for the official 3.0 release first (and most probably its really easy to update this just now if needed), but sometimes I avoid previews due to tooling might be a bit frustrating sometimes

**Comment by stephenlautier** [comment]
after some swearing.. template is updated to .netcore3 and angular 8.2.9

If you try it out let me know how it goes!
